- name: Install packages
  ansible.builtin.import_tasks: dnf.yml
- name: Checkout repository
  ansible.builtin.import_tasks: git-checkout.yml
- name: Branch repository
  ansible.builtin.import_tasks: git-branch.yml
- name: Patch repository
  ansible.builtin.import_tasks: patch.yml
- name: Build Container
  ansible.builtin.import_tasks: build-fedora.yml
- name: Tag Container
  ansible.builtin.import_tasks: tag-fedora.yml
- name: Push Container
  ansible.builtin.import_tasks: push-fedora.yml
